service: shippable-boilerplates-serverless-backend
provider:
    name: aws
    runtime: nodejs6.10
    region: us-east-2
package:
    individually: true
    exclude:
        - .git/**
functions:
    getRandomFact:
        description: Gets a random Chuck Norris fact from ChuckDB
        handler: functions/getRandomFact/handler.handler
        memorySize: 256
        timeout: 5
        events:
            - http:
                path: random-fact
                method: GET
                cors: true
